CREATE DATABASE movies;
GRANT ALL PRIVILEGES ON DATABASE movies TO postgres;
CREATE DATABASE user;
GRANT ALL PRIVILEGES ON DATABASE user TO postgres;
CREATE DATABASE refresh_tokens;
GRANT ALL PRIVILEGES ON DATABASE refresh_tokens TO postgres;
